"""Write public/_headers: browser security rules Cloudflare sends with every page and file.

The Content-Security-Policy allows the page's own inline script only by its exact
fingerprint (sha256), so this runs at the end of gen_site.py and gen_pages.py and
picks up any edit automatically. Everything else the site loads comes from its own
domain, plus Cloudflare Turnstile (the quote form's spam check)."""
import base64, glob, hashlib, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
PUBLIC = os.path.join(HERE, '..', 'public')


def inline_script_hashes():
    hashes = []
    for path in sorted(glob.glob(os.path.join(PUBLIC, '*.html'))):
        html = open(path, encoding='utf-8').read()
        for m in re.finditer(r'<script(?![^>]*\bsrc=)(?![^>]*ld\+json)[^>]*>(.*?)</script>', html, re.S):
            h = "'sha256-" + base64.b64encode(hashlib.sha256(m.group(1).encode('utf-8')).digest()).decode() + "'"
            if h not in hashes:
                hashes.append(h)
    return hashes


def main():
    csp = '; '.join([
        "default-src 'self'",
        "script-src 'self' " + ' '.join(inline_script_hashes()) + " https://challenges.cloudflare.com",
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data: blob:",
        "font-src 'self'",
        "connect-src 'self'",
        "frame-src https://challenges.cloudflare.com",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
        "frame-ancestors 'none'",
        "upgrade-insecure-requests",
    ])
    rules = f"""# Generated by gen_headers.py. Edit that script, not this file.
/*
  Content-Security-Policy: {csp}
  Strict-Transport-Security: max-age=31536000
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()
  Cross-Origin-Opener-Policy: same-origin
"""
    for line in rules.splitlines():
        assert len(line) < 2000, 'a _headers line is over 2,000 characters'
    open(os.path.join(PUBLIC, '_headers'), 'w').write(rules)
    print('wrote _headers with', len(inline_script_hashes()), 'script fingerprints')


main()
